### ISSUE TITLE
Cannot find module '../internals/export'

### ISSUE THREAD

**Issue by vajajak** [csandman/yup-phone-lite#12]
Hi,
first of all, i'd like to thank you for implementing https://github.com/csandman/yup-phone-lite/issues/9 so quickly.

However, since upgrading to version 1.2.0, I'm experiencing this cryptic import error when using in a Next.js project. The problem disappears when I downgrade back to 1.1.2. I would love to use the new "multiple country code" feature introduced in 1.2.0 though :).

The version of Next.js is 12.2.0, i'm running Node v14.20.1 with npm 8.19.2, if that matters.

This is the error I'm getting:

```
error - Error: Cannot find module '../internals/export'
Require stack:
- /Users/vajajak/cdp-ivory/fe/node_modules/yup-phone-lite/dist/yup-phone-lite.cjs.js
- /Users/vajajak/cdp-ivory/fe/.next/server/pages/dashboard/users/create.js
- /Users/vajajak/cdp-ivory/fe/node_modules/next/dist/server/require.js
- /Users/vajajak/cdp-ivory/fe/node_modules/next/dist/server/next-server.js
- /Users/vajajak/cdp-ivory/fe/node_modules/next/dist/server/next.js
- /Users/vajajak/cdp-ivory/fe/node_modules/next/dist/server/lib/start-server.js
- /Users/vajajak/cdp-ivory/fe/node_modules/next/dist/cli/next-dev.js
- /Users/vajajak/cdp-ivory/fe/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.mod._resolveFilename (/Users/vajajak/cdp-ivory/fe/node_modules/next/dist/build/webpack/require-hook.js:182:28)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/vajajak/cdp-ivory/fe/node_modules/yup-phone-lite/dist/yup-phone-lite.cjs.js:2:54)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/vajajak/cdp-ivory/fe/node_modules/yup-phone-lite/dist/yup-phone-lite.cjs.js',
    '/Users/vajajak/cdp-ivory/fe/.next/server/pages/dashboard/users/create.js',
    '/Users/vajajak/cdp-ivory/fe/node_modules/next/dist/server/require.js',
    '/Users/vajajak/cdp-ivory/fe/node_modules/next/dist/server/next-server.js',
    '/Users/vajajak/cdp-ivory/fe/node_modules/next/dist/server/next.js',
    '/Users/vajajak/cdp-ivory/fe/node_modules/next/dist/server/lib/start-server.js',
    '/Users/vajajak/cdp-ivory/fe/node_modules/next/dist/cli/next-dev.js',
    '/Users/vajajak/cdp-ivory/fe/node_modules/next/dist/bin/next'
  ],
  page: '/dashboard/users/create'
}
```

Thanks in advance for taking a look at this :)

**Comment by csandman** [comment]
Ok, after a while of banging my head in the wall trying to figure out what I broke about the other build, I decided to change the package's approach entirely, away from the `rollup`. The whole rollup setup was mostly made by the author of the original package `yup-phone`, so I never got entirely familiar with it.  I ended up making the build process for this package much more similar to another package I maintain, which allowed my to remove a bunch of dependencies, and it seems to work much better.

If you have any issues getting this to work, or if any new issues crop up, definitely let me know!

**Comment by alxndrsn** [comment]
I started seeing this error with 1.1.2 on a project which built fine in early December last year.

I tried updating to 1.2.0 (same error), 2.0.1 (something else broke: `_libphonenumberJs.isSupportedCountry is not a function`).

Reverting to 1.1.0 fixed the problem.

Happy to investigate further if it would be helpful.

**Comment by csandman** [comment]
@alxndrsn  That's odd, I can't seem to make that issue happen. Can you give me some more info about your environment? Node version, how you're using the package (web, node), other dependencies?

Also, have you tried doing a fresh installation of the package? it seems like the libphonenumber-js package might not be getting recognized somehow, or is on the incorrect version.

**Comment by alxndrsn** [comment]
@csandman This is for a node project.  I only see `Error: Cannot find module '../internals/export'` in CI (github actions), where I assume the package is installed fresh every time.  I've disabled the github actions yarn cache, and still get the same error.  Dependencies are pinned with `yarn.lock`, and I have re-run the build with the same node version that worked in early December.
