### ISSUE TITLE
UK is not supported

### ISSUE THREAD

**Issue by TarekAlQaddy** [csandman/yup-phone-lite#18]
When I try to add a phone number validation to the schema like so `yup.string().phone('UK')` it falls back to using US, The allowed country code is GB only.
I saw here https://github.com/csandman/yup-phone-lite/blob/main/src/yup-phone-lite.test.ts#L63C29-L63C29  the test says `validate phone number with GB (United Kingdom) region` but GB !== UK

**Comment by csandman** [comment]
For all intents and purposes, they are the same. The list of codes is an official list of [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country codes, of which `UK` is not a part of. If you search for "UK" on that page, you can find a few references they make that allude to them treating United Kingdom and Great Britain the same.

As for Northern Ireland, their local numbers can be used as either a local variant (Ireland) or a UK variant. Only the variant specific to that place will pass each check. See: https://en.wikipedia.org/wiki/Telephone_numbers_in_the_Republic_of_Ireland#Calls_to_Northern_Ireland

If you want to allow both Great Britain and Ireland phone numbers, just pass an array of `["GB", "IE"]`.
