### ISSUE TITLE
Accept optional value if field is not required

### ISSUE THREAD

**Issue by viclafouch** [csandman/yup-phone-lite#3]
Hello ! 

# Description

There is a bug when we want a field to be optional, but we still have an error : 

in my case : `parameters.phone must be a valid phone number for region FR` 

```js
phone: yup.string().phone('FR').optional()
// or
phone: yup.string().phone('FR')
```

If I fill the field, and then, remove my value,  or, just focus the empty field, and then, and focusout, I have still the error, even if I put my field `.optional()`.

# Solution

If the field is empty and not required, just valid it.

# Screenshot

![image](https://user-images.githubusercontent.com/23353836/131130869-dd608df1-61a1-481e-b47f-39a96419280c.png)

**Comment by lubomirKavetskiy** [comment]
@viclafouch could you plz tell how you resolved your case, have the same
