### ISSUE TITLE
Allow All Countries

### ISSUE THREAD

**Issue by aress31** [csandman/yup-phone-lite#5]
This lib is brilliant and much muvh smaller than the original one, however a big drawback is that a country code must be specified, I want to allow anyone to input their numbers on my forms regardless of their country. Once this will be addressed, this lib will be perfect!

**Comment by csandman** [comment]
Unfortunately, there is no consistent way to implement this with the [libphonenumber-js](https://www.npmjs.com/package/libphonenumber-js) package.  I mention that in the description.

I tried to implement it in a few ways and it was very inconsistent.  If thats really what you're looking for, by all means go for the original package!
