### ISSUE TITLE
How to allow multiple country code?

### ISSUE THREAD

**Issue by reyn-nova** [csandman/yup-phone-lite#9]
For example I want my phone number field allowed only Malaysia and Singapore? It can be filled one of them

**Comment by vajajak** [comment]
I managed to get this working by passing an array of country codes. Even though the Typescript will complain it works. You can optionally silence the ts error by `// @ts-ignore`

**Comment by csandman** [comment]
@vajajak Based on the code in this plugin, if you pass an array like that the values will just be replaced with `"US"`, and won't work as you expect it to.

I can however change the code to allow an array of country codes as an alternative.

**Comment by csandman** [comment]
I added the option to pass an array of country codes in [v1.2.0](https://github.com/csandman/yup-phone-lite/releases/tag/v1.2.0). If you have any problems getting this to work, feel free to reopen the issue.
